FROM node:alpine AS client

USER node
RUN mkdir -p /home/node/app
RUN mkdir /home/node/.npm-global
ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

WORKDIR /home/node/app
COPY --chown=node:node ./package.json package-lock.json ./
RUN npm install
RUN npm install -g @angular/cli@12.0.0
COPY --chown=node:node . .


CMD ["ng", "serve", "--port", "4200", "--host", "0.0.0.0", "--disable-host-check", "--poll", "2000"]