sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t speedforce7/angular-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true speedforce7/angular-test npm run testcov

after_success:
  - docker build -t speedforce7/tourism-client ./client
  - docker build -t speedforce7/tourism-nginx ./nginx
  - docker build -t speedforce7/tourism-api ./webapi

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push speedforce7/tourism-client
  - docker push speedforce7/tourism-nginx
  - docker push speedforce7/tourism-api
