sudo: required
language: generic

services:
  - docker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "tourism-app"
  env: "Tourismapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-306483622823"
  bucket_path: "tourism-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
