version: '3.4'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=$PGDATABASE
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_USER=$PGUSER
    volumes:
      - ./postgres-data:/var/lib/postgresql/store
