version: '3.4'

services:
  tourism.webapp:
    image: ${DOCKER_REGISTRY-}tourismserver
    build:
      context: .
      dockerfile: Tourism.WebApp/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgress_db
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "tourism-db-dev:5432", "--", "dotnet", "Tourism.WebApp.dll"]
    environment:
      DB_USER: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_HOST: 'postgress_db'
      DB_PORT: 5432
      DB_NAME: 'tourism-db-dev'

  postgress_db:
    container_name: postgress_db
    image: postgres:12.3
    #    This folder tell docker compose, where postgres data will be stored, before ":" - local folder, after - in the container
    volumes:
      - ./postgres-data:/var/lib/postgresql/store
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: 'tourism-db-dev'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'

  tourism.angular:
    image: ${DOCKER_REGISTRY-}tourismangularapp
    build:
      context: .
      dockerfile: Tourism.WebApp/ClientApp/Dockerfile
    ports:
      - "4200:4200"
      - "49153:49153"
    depends_on:
      - tourism.webapp
    volumes:
      - ./Tourism.WebApp/ClientApp:/app


   