version: '3.4'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'tourism'
      POSTGRES_PASSWORD: 'postgres_password'
      POSTGRES_USER: 'postgres'
    volumes:
      - ./postgres-data:/var/lib/postgresql/store
    ports:
      - "9999:5432"
  nginx:
    depends_on:
      - tourism-api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8888:80"
  tourism-api:
    image: ${DOCKER_REGISTRY-}tourism-api
    build:
      context: ./webapi
      dockerfile: Dockerfile
    depends_on:
      - postgres
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "postgres:5432", "--", "dotnet", "Tourism.WebApp.dll"]
    environment:
      - POSTGRES_USER=postgres
      - PGHOST=postgres
      - POSTGRES_DB=tourism
      - POSTGRES_PASSWORD=postgres_password
      - PGPORT=5432   
    ports:
      - "5000:5000"
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /home/node/app/node_modules
      - ./client:/home/node/app


   