version: '3.4'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=$PGDATABASE
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_USER=$PGUSER
    volumes:
      - ./postgres-data:/var/lib/postgresql/store
  nginx:
    depends_on:
      - tourism-api
      - client
    restart: always
    mem_limit: 128m
    hostname: nginx
    image: speedforce7/tourism-nginx
    ports:
      - "80:80"
  tourism-api:
    image: speedforce7/tourism-api
    depends_on:
      - postgres
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "postgres:5432", "--", "dotnet", "Tourism.WebApp.dll"]
    environment:
      - POSTGRES_USER=$PGUSER
      - PGHOST=$PGHOST 
      - POSTGRES_DB=$PGDATABASE
      - POSTGRES_PASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
    hostname: tourism-api
  client:
    image: "speedforce7/tourism-client"
    mem_limit: 128m
    hostname: client
