version: '3.4'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGUSER=$PGUSER
    volumes:
      - ./postgres-data:/var/lib/postgresql/store