version: '3.4'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=tourism-db
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/store
    ports:
      - "9999:5432"
 
  tourism-api:
    image: ${DOCKER_REGISTRY-}tourism-api
    build:
      context: .
      dockerfile: Tourism.WebApp/Dockerfile
    depends_on:
      - postgres
    entrypoint: ["/usr/local/bin/wait-for-it.sh", "postgres:5432", "--", "dotnet", "Tourism.WebApp.dll"]
    environment:
      - POSTGRES_USER=postgres
      - PGHOST=postgres
      - POSTGRES_DB=tourism-db
      - POSTGRES_PASSWORD=postgres_password
      - PGPORT=$PGPORT
      - ASPNETCORE_ENVIRONMENT=$ASPNETCORE_ENVIRONMENT
    ports:
      - "5000:5000"
  


   